version: '3'
networks:
  proxy:
    driver: overlay
    
services:
  traefik:
    image: davidtre07/traefik:1.2.0-rc2
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - /docker/config/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - proxy


  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock --no-analytics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.frontend.rule="Host:portainer, portainer.lan, swarm, swarm.lan"
        - traefik.port=9000
    networks:
      - proxy 

  nginx:
    image: davidtre07/nginx
    volumes:
      - /docker/config/nginx:/etc/nginx
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.frontend.rule="Host:domotique, domotique.lan"
        - traefik.port=80
    networks:
      - proxy


  domoticz:
    image: davidtre07/domoticz-beta:latest
    ports:
      - "18080:8080"
    volumes:
      - /docker/config/domoticz:/config:rw
      - /docker/data/gcalcli:/data:rw
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=false
    networks:
      - proxy

  visualizer:
    image: alexellis2/visualizer-arm:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.frontend.rule="Host:viz, viz.lan"
        - traefik.port=8080
    networks:
      - proxy

  nodeExporter:
    image: davidtre07/node-exporter
    command: -collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)" --collectors.enabled="conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat,ipvs"
    network_mode: "host"
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc
      - /sys:/hosts/sys
      - /:/rootfs
    deploy:
      mode: global
      labels:
        - traefik.enable=false



