version: '3'
networks:
  proxy2:
    driver: overlay
    
services:
  traefik:
    image: davidtre07/traefik:1.2.0-rc2
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - /docker/config/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - proxy2


  domoticz:
    image: davidtre07/domoticz-beta:latest
    volumes:
      - /docker/config/domoticz:/config:rw
      - /docker/data/gcalcli:/data:rw
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.frontend.rule="Host:domotique, domotique.lan"
        - traefik.port=8080
    networks:
      - proxy2

